version: '3'
services:
  db:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose: 
      - 5432
    ports:
      - 5432:5432
    
  web:
    #build: ./docker/web
    image: nimmis/alpine-apache-php7
    volumes: 
      - ./src:/web/html
      - ./docker/web/config/httpd.conf:/etc/apache2/httpd.conf
    ports:
      - 9000:80
    depends_on:
      - db
    links:
      - "db:database"